import "./globals.css";
import Navbar from "@/app/components/Navbar";

export const metadata = {
  title: "Evolvelnfi",
  description: "Generated by Evolvelnfi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-geist antialiased">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
